parameters:
    pim_excel_connector.array_converter.flat_to_standard.attribute.class: Pim\Bundle\ExcelConnectorBundle\ArrayConverter\Flat\Attribute

services:
    pim_excel_connector.array_converter.flat_to_standard.attribute:
        class: '%pim_excel_connector.array_converter.flat_to_standard.attribute.class%'
        parent: 'pim_connector.array_converter.flat_to_standard.attribute'
