parameters:

services:
    pim_excel_connector.step.init.attribute_groups:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import_attribute_groups'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_excel_connector.reader.xls_init.attribute_group'
            - '@pim_connector.processor.denormalization.attribute_group'
            - '@pim_connector.writer.database.attribute_group'

    pim_excel_connector.step.init.categories:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import_categories'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_excel_connector.reader.xls_init.category'
            - '@pim_connector.processor.denormalization.category'
            - '@pim_connector.writer.database.category'

    pim_excel_connector.step.init.channels:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import_channels'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_excel_connector.reader.xls_init.channel'
            - '@pim_connector.processor.denormalization.channel'
            - '@pim_connector.writer.database.channel'

    pim_excel_connector.step.init.group_types:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import_group_types'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_excel_connector.reader.xls_init.group_type'
            - '@pim_connector.processor.denormalization.group_type'
            - '@pim_connector.writer.database.group_type'

    pim_excel_connector.step.init.association_types:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'import_association_type'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_excel_connector.reader.xls_init.association_type'
            - '@pim_connector.processor.denormalization.association_type'
            - '@pim_connector.writer.database.association_type'
